---
version: '3.4'
services:
  script:
    image: 'node:10.20.1-stretch'
    working_dir: /app
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app
      - 'modules:/app/node_modules'
    environment:
      - DD_ENV=test
      - DD_SERVICE=dd-trace-test-script
      - DD_AGENT_HOST=agent
      - DD_TRACE_AGENT_PORT=8126
    networks:
      - script
  postgres:
    image: 'postgres:9.5.16'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - script
  agent:
    image: datadog/agent
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_API_KEY
    ports:
      - '8126:8126'
    networks:
      - script

volumes:
  modules:

networks:
  script:
